apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service-production
  namespace: argocd
spec:
  project: release-platform
  source:
    repoURL: https://github.com/Release-Orchestrator/release-orchestrator
    targetRevision: main
    path: k8s-manifests/user-service/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
